// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPbVtdqrDO5j55TYx7Upcj7SL-1eb9yuU',
    appId: '1:242718631111:web:b7304c41b2eba50227cae2',
    messagingSenderId: '242718631111',
    projectId: 'insuguia',
    authDomain: 'insuguia.firebaseapp.com',
    storageBucket: 'insuguia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7MZPHK2Hd3GYM5Xv28EBkKZIHiIQ14zY',
    appId: '1:242718631111:android:d20a1b033a61b94227cae2',
    messagingSenderId: '242718631111',
    projectId: 'insuguia',
    storageBucket: 'insuguia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2L4UfkFOCr2Q-kTWQQglBnrS_DdVTOw',
    appId: '1:242718631111:ios:8c8bd9bc90b07a7327cae2',
    messagingSenderId: '242718631111',
    projectId: 'insuguia',
    storageBucket: 'insuguia.firebasestorage.app',
    iosBundleId: 'com.example.insuguia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPbVtdqrDO5j55TYx7Upcj7SL-1eb9yuU',
    appId: '1:242718631111:web:a142d8910b43423727cae2',
    messagingSenderId: '242718631111',
    projectId: 'insuguia',
    authDomain: 'insuguia.firebaseapp.com',
    storageBucket: 'insuguia.firebasestorage.app',
  );
}
