import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';
import 'tela_cadastro.dart';
import 'tela_registro_insulina.dart';
import 'tela_historico.dart';
import 'tela_login.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase with platform-specific options generated by
  // `flutterfire configure`. If you haven't run that yet, the app will
  // still initialize but you'll need to run the configure command to
  // generate `firebase_options.dart`.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const InsuGuiaApp());
}

class InsuGuiaApp extends StatelessWidget {
  const InsuGuiaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'InsuGuia Mobile',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: Colors.blue[50],
      ),
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          
          if (snapshot.hasData && snapshot.data != null) {
            return const TelaPrincipal();
          }
          
          return const TelaLogin();
        },
      ),
      debugShowCheckedModeBanner: false,
    );
  }
}

class TelaPrincipal extends StatelessWidget {
  const TelaPrincipal({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('InsuGuia Mobile'),
        centerTitle: true,
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () => FirebaseAuth.instance.signOut(),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'Aplicativo acadêmico para apoio à prescrição de insulina '
              'em pacientes hospitalares (cenário não crítico).',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 30),
            ElevatedButton.icon(
              icon: const Icon(Icons.person_add),
              label: const Text('Cadastro de Paciente'),
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (_) => const TelaCadastro()));
              },
            ),
            const SizedBox(height: 10),
            ElevatedButton.icon(
              icon: const Icon(Icons.medication),
              label: const Text('Registrar Dose de Insulina'),
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (_) => const TelaRegistroInsulina()));
              },
            ),
            const SizedBox(height: 10),
            ElevatedButton.icon(
              icon: const Icon(Icons.history),
              label: const Text('Histórico de Aplicações'),
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (_) => const TelaHistorico()));
              },
            ),
          ],
        ),
      ),
    );
  }
}
